// Supabase Edge Function: analyze-meal
// Integrates with Google Gemini Flash Multimodal Vision API to detect meals and estimate portion weights and macros.

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY") || "";

const NUTRITION_SYSTEM_PROMPT = `
You are an expert clinical dietitian and computer vision nutritionist.
Analyze the user's meal photo and estimate the food items, their approximate weight in grams, and their macronutrients (calories, protein, carbohydrates, fats).

Guidelines:
1. Identify all distinguishable food components on the plate/container.
2. Estimate the realistic portion weight in grams based on visual cues, plate proportions, and typical serving sizes.
3. Compute macronutrients based on USDA standard reference values.
4. If has_added_oil is true, factor in 10-15g of added cooking oil/butter.
5. Provide a confidence score between 0.0 and 1.0.
6. Provide brief estimation notes explaining your serving size assumptions.
`;

const RESPONSE_SCHEMA = {
  type: "OBJECT",
  properties: {
    meal_title: { type: "STRING" },
    items: {
      type: "ARRAY",
      items: {
        type: "OBJECT",
        properties: {
          name: { type: "STRING" },
          portion_grams: { type: "NUMBER" },
          calories: { type: "INTEGER" },
          protein: { type: "NUMBER" },
          carbs: { type: "NUMBER" },
          fat: { type: "NUMBER" },
          confidence: { type: "NUMBER" }
        },
        required: ["name", "portion_grams", "calories", "protein", "carbs", "fat"]
      }
    },
    total_calories: { type: "INTEGER" },
    total_protein: { type: "NUMBER" },
    total_carbs: { type: "NUMBER" },
    total_fat: { type: "NUMBER" },
    confidence: { type: "NUMBER" },
    estimation_notes: { type: "STRING" }
  },
  required: ["meal_title", "items", "total_calories", "total_protein", "total_carbs", "total_fat", "confidence"]
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", {
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "POST",
        "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type"
      }
    });
  }

  try {
    const { image_base64, has_added_oil, user_note } = await req.json();

    if (!image_base64) {
      return new Response(JSON.stringify({ error: "Missing image_base64" }), {
        status: 400,
        headers: { "Content-Type": "application/json" }
      });
    }

    if (!GEMINI_API_KEY) {
      return new Response(JSON.stringify({ error: "GEMINI_API_KEY not configured on server" }), {
        status: 500,
        headers: { "Content-Type": "application/json" }
      });
    }

    const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}`;

    const promptText = `
Analyze this meal.
Added cooking oil/butter: ${has_added_oil ? "YES" : "NO"}.
${user_note ? `User context: "${user_note}".` : ""}
Return strictly structured JSON matching the requested schema.
`;

    const requestPayload = {
      contents: [
        {
          parts: [
            { text: promptText },
            {
              inline_data: {
                mime_type: "image/jpeg",
                data: image_base64
              }
            }
          ]
        }
      ],
      system_instruction: {
        parts: [{ text: NUTRITION_SYSTEM_PROMPT }]
      },
      generationConfig: {
        response_mime_type: "application/json",
        response_schema: RESPONSE_SCHEMA,
        temperature: 0.2
      }
    };

    const response = await fetch(geminiUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestPayload)
    });

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`Gemini API Error: ${response.status} - ${errText}`);
    }

    const data = await response.json();
    const candidateText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!candidateText) {
      throw new Error("No response generated by Gemini model");
    }

    const parsedJson = JSON.parse(candidateText);

    return new Response(JSON.stringify(parsedJson), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": "*"
      }
    });

  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": "*"
      }
    });
  }
});
